export enum EnvVarsEnum {
  'NODE_ENV' = 'NODE_ENV',
  'PORT' = 'PORT',
  'DATABASE_CONFIG' = 'DATABASE_CONFIG',
  'DATABASE_TYPE' = 'DATABASE_TYPE',
  'DATABASE_URL' = 'DATABASE_URL',
  'DATABASE_NAME' = 'DATABASE_NAME',
  'DATABASE_HOST' = 'DATABASE_HOST',
  'DATABASE_PORT' = 'DATABASE_PORT',
  'DATABASE_USERNAME' = 'DATABASE_USERNAME',
  'DATABASE_PASSWORD' = 'DATABASE_PASSWORD',
  'DATABASE_DATATIME_TYPE' = 'DATABASE_DATATIME_TYPE',
  'MAIN_ADMIN_USERNAME' = 'MAIN_ADMIN_USERNAME',
  'MAIN_ADMIN_PASSWORD' = 'MAIN_ADMIN_PASSWORD',
  'MAIN_ADMIN_NAME' = 'MAIN_ADMIN_NAME'
}
